### ISSUE TITLE
[PE-D] Save/Load error if I use "|" in the fields 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F12-1/tp#48]
If I use " | " as part of the description, the save / load messes up

![image.png](https://raw.githubusercontent.com/Teanweijun/ped/main/files/56df1e31-1886-4e16-96cc-f44380049d8c.png)

![image.png](https://raw.githubusercontent.com/Teanweijun/ped/main/files/4e345705-95ba-4b6c-a113-4bb0f119c873.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Teanweijun/ped#4

**Comment by striris** [comment]
can put 'do not change the content of file'' in user guide and show in the terminal 
ug add a constraint for i put:  and don't use '|' in the input field
